name: "njmu_prostate_3d"

task:
  num_classes: 4
  include_background_in_mean: false
  ignore_index: null
  label_map:
    0: 0
    1: 1
    2: 2
    3: 3

paths:
  raw_dir: "E:/NJMU_prostate_data/Datasets004_NJMU_prostate"
  splits_dir: "data/splits/njmu_prostate_3d"

raw_structure:
  images_tr_dir: "ImagesTr"
  labels_tr_dir: "LabelsTr"
  images_ts_dir: "ImagesTs"
  labels_ts_dir: "LabelsTs"
  modality_suffixes: ["_0000.nii.gz", "_0001.nii.gz", "_0002.nii.gz"]

input:
  image_channels: 3
  spatial_size: [160, 160, 32]
  roi_size: [160, 160, 32]

intensity:
  mode: "percentile"
  percentile_clip: [0.5, 99.5]

split:
  type: "train_5fold_test_fixed"
  folds: 5
  seed: 42
  group_key: "patient_id"